test('should throw when not authorized', () => {
  // TODO: write a test that fails due to the bug in
  // Calculator.divide()

})
